application: my-food-tracker
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: liquid_and_calorie_tracker.application

libraries:
- name: webapp2
  version: latest
